E2E test to fetch signature from authenticated registry.
kubewarden/policy-fetcher pull request #186
Opened 2024-05-07 02:48 UTC by jvanz

## Description

Add a test to verify if the policy fetch is able to fetch the Sigstore data from an authenticated registry.

Fix https://github.com/kubewarden/policy-fetcher/issues/181

## Test

```shell
make test
```

2024-05-07 11:47 UTC, jvanz commented on tests/e2e.rs
> +    std::env::set_var("DOCKER_CONFIG", auth_dir.path());
I do not like this. But the lib used to find the config file uses env var to find the file

2024-05-07 14:17 UTC, viccuad commented on tests/e2e.rs
> +    std::env::set_var("DOCKER_CONFIG", auth_dir.path());
I do not like that the env vars are let set for the rest of the tests. We don't consume those env vars though so I consider it fine.

2024-05-07 14:17 UTC, viccuad commented on tests/e2e.rs
> +    // pulling policy image. webassembly.azurecr.io/hello-wasm:v1
```suggestion
    // pulling policy image
```

2024-05-07 14:18 UTC, viccuad approved these changes
LGTM. I would prefer the test first on the file and then the aux functions, but it's fine as it is.

2024-05-08 12:44 UTC, jvanz commented
> Mac e2e fail on testcontainers :/.

Github Mac runner image does not have Docker [installed by default](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md). :tired_face:

2024-05-08 18:24 UTC, jvanz commented
@kubewarden/kubewarden-developers I've tried to install docker in the MacOS to run the added test on it as well. But I've run into an issue on QEMU/Colima starting. Which was consuming some time. Thus, I've decided to disable the test on Mac and leave this issue for later.

2024-05-09 12:31 UTC, flavio requested changes

2024-05-09 12:31 UTC, flavio commented on tests/e2e.rs
> +use sigstore::registry::OciReference;
can you group all the imports together? LSP has a handy shortcut to do that (at least with vim)

2024-05-09 12:31 UTC, flavio commented on tests/e2e.rs
> +) -> Result<(), String> {
I would just use anyhow here, make it a dev dependency. It would simplify the code below (no need to do `map_err` for example), otherwise... instead of mapping the error and bubbling it up, just do an `expect`

2024-05-09 12:31 UTC, flavio commented on tests/e2e.rs
> +        .expect("unexpected error");
should be something that provides context to the error, like "cannot create signer"

2024-05-09 12:31 UTC, flavio commented on tests/e2e.rs
> +async fn load_container_image(port: u16) -> Reference {
nitpick: `push` would be better than `load` IMHO

2024-05-09 12:31 UTC, flavio commented on tests/e2e.rs
> +async fn load_container_image(port: u16) -> Reference {
I would also split that into these functions:

- `pull_image(uri: &str)`
- `push_image(dest_uri: &str, image_data whatever_is_returned_by_oci_image_pull)`
- `sign_image`

2024-05-09 12:31 UTC, flavio commented on tests/e2e.rs
> +use policy_fetcher::verify::fetch_sigstore_remote_data;
I'm fine not running this test on macos, however the linter is complaining about a bunch of stuff. It would be great to avoid these warnings.

I see two possible solutions:
- create a `tests/mod.rs` which enables the `e2e.rs` test on non-macos arch. I wonder if that works...
- add some clippy directives to suppress warnings. these should be turned on only on mac

2024-05-09 12:31 UTC, flavio commented on tests/e2e.rs
> +    let port = container.get_host_port_ipv4(5000);
The `5000` should be a const

2024-05-09 12:31 UTC, flavio commented on tests/e2e.rs
> +    fetch_sigstore_remote_data(&client_arc, &format!("registry://{}", push_image.whole()))
Can we test the actual pulling of the image and it's verification? Basically what kwctl pull would do.

2024-05-10 18:56 UTC, jvanz commented on tests/e2e.rs
> +use policy_fetcher::verify::fetch_sigstore_remote_data;
I think the first option is not possible because cargo compiles all the files under "tests" directory as crate running tests. 

> We create a tests directory at the top level of our project directory, next to src. Cargo knows to look for integration test files in this directory. We can then make as many test files as we want, and Cargo will compile each of the files as an individual crate.

I think if we reorg how we run all the tests here we may be able to do that. But I think that should be in a different PR. I'll try follow the second approach.

2024-05-10 20:42 UTC, jvanz commented
@kubewarden/kubewarden-developers I'm aware of the windows failing tests. I'll take a look on it next week.

2024-05-21 09:19 UTC, flavio approved these changes
LGTM. thanks for the changes

2024-05-21 09:19 UTC, merged