feature: implement policy store
kubewarden/policy-fetcher pull request #2
Opened 2021-04-30 15:52 UTC by ereslibre

2021-05-01 07:13 UTC, flavio requested changes
Everything looks good, on top of the comment I left I have two observations:

* This changes from the `native-tls`  to `rusttls`. This is cool from a certain POV, I'm thinking about a statically linked `kwctl` binary. However, this crate will be used also inside of the `policy-server`, which is stuck with the `native-tls` crate. I don't think this will cause issues, do you?
* We really need some tests for the methods that you introduced, like the ones that build all the paths for the local store. I'm not saying we have to go "crazy" and provide e2e tests that download things from real registries/http/https servers, but there are definitely some low hanging fruits from the testing POV that we must grab

2021-05-01 07:13 UTC, flavio commented on src/https.rs
> +                        reqwest::Certificate::from_der(certificate.as_ref())?,
This is going to choke on PEM encoded certificates. Reqwest has a `Certificate::from_pem` method too, we should integrate that.

Plus the library should automatically figure out what is the encoding of the certificate. We can relay on file extension, plus check for the ASCII header of the pem certificates...

2021-05-03 08:13 UTC, ereslibre commented
> This changes from the native-tls to rusttls. This is cool from a certain POV, I'm thinking about a statically linked kwctl binary. However, this crate will be used also inside of the policy-server, which is stuck with the native-tls crate. I don't think this will cause issues, do you?

I don't think so, in principle. The policy-server will do the TLS termination of the requests made by the apiserver, whereas when fetching policies we'll use rustls. They have different CA default stores -- meaning, rustls has its own main CA store, while native-tls uses the system one.

I think we can add a task for checking if this is the best combination and possible hazards later. Meaning: for doing the TLS termination we don't care that much about root CA certificates (and we are using the system certs by using native-tls at this time), but we care a lot about the CA store of the policy-fetcher (using rustls). How secure is to rely on rustls for this? Before bumping dependencies in this case we should check that the store included by rustls only contains well-known CA's, and only those well known, nothing more.

> We really need some tests for the methods that you introduced, like the ones that build all the paths for the local store. I'm not saying we have to go "crazy" and provide e2e tests that download things from real registries/http/https servers, but there are definitely some low hanging fruits from the testing POV that we must grab

:+1:

2021-05-03 08:38 UTC, ereslibre commented on src/https.rs
> +                        reqwest::Certificate::from_der(certificate.as_ref())?,
I went with the straightforward way: first try PEM, otherwise try DER. If both fail, return error. No need to be smart here.

2021-05-03 10:12 UTC, flavio commented on src/https.rs
> +                        reqwest::Certificate::from_der(certificate.as_ref())?,
Sounds reasonable to me :)

2021-05-03 10:14 UTC, flavio approved these changes
LGTM, please... start working on the test suite

2021-05-03 15:06 UTC, merged