expose fetch manifest digest
kubewarden/policy-fetcher pull request #26
Opened 2021-11-16 13:34 UTC by flavio

Expose a method to fetch the manifest digest. This is needed so that we can expose this function to our policies.

While at that, I also did some refactoring of function params: from `&Option<T>` to `Option<&T>`.

2021-11-22 10:43 UTC, flavio commented
This is now ready for review.

2021-11-22 17:50 UTC, ereslibre requested changes
LGTM except for some comments.

2021-11-22 17:50 UTC, ereslibre commented on src/registry/mod.rs
> +        let sources: Sources = sources.cloned().unwrap_or_default();
Given `manifest` returns a `Result`, I'd bubble the error up (or map the error) if `cloned()` fails instead of silently defaulting the structure.

2021-11-22 17:50 UTC, ereslibre commented on src/registry/mod.rs
> +            Reference::from_str(url.as_ref().strip_prefix("registry://").unwrap_or_default())?;
I think we want to bubble the error up as well here, falling back to the default would end up in `Reference::from_str(String::default))` what could lead to errors hard to understand on the user side.

2021-11-22 17:50 UTC, ereslibre commented on src/registry/mod.rs
> +        let sources: Sources = sources.cloned().unwrap_or_default();
We should bubble up here as well I think.

2021-11-23 08:10 UTC, viccuad reviewed
LGTM modulo the points raised by Rafa, which I agree with.

2021-11-23 08:16 UTC, ereslibre commented on src/registry/mod.rs
> +        let sources: Sources = sources.cloned().unwrap_or_default();
NVM, I just realized `cloned()` just returns an `Option` on `Option`. I see, is a way to not consume the `Option` because `unwrap_or_default()` consumes it, right?

In that case, discard the rest of my comments in the same direction.

2021-11-23 08:19 UTC, flavio commented on src/registry/mod.rs
> +        let sources: Sources = sources.cloned().unwrap_or_default();
yes, that's the case. I'll resolve the other comments you left

2021-11-23 08:28 UTC, flavio commented on src/registry/mod.rs
> +            Reference::from_str(url.as_ref().strip_prefix("registry://").unwrap_or_default())?;
Good point, I have to admit I copied and pasted this snippet from other parts of the code. I've changed it now, can you take another look?

2021-11-23 08:44 UTC, ereslibre approved these changes

2021-11-23 08:52 UTC, viccuad commented on src/registry/mod.rs
> +        let sources: Sources = sources.cloned().unwrap_or_default();
doh, indeed, now I see it too. Thanks both!

2021-11-23 08:53 UTC, viccuad approved these changes

2021-11-23 10:07 UTC, merged