Windows path fixes
kubewarden/policy-fetcher pull request #40
Opened 2022-01-26 10:41 UTC by ereslibre

Fix policy store path handling in Windows:

- Replace colons (illegal character name for paths) with a fake colon. This allows us to not do anything special for Windows in terms of policy store structure.
- Always use forward slashes for URL's

2022-01-26 11:38 UTC, viccuad reviewed
The code looks fine, but I really wonder about using an utf8 char that looks like a colon.
If I were a Windows user, and I need to type the path, it wouldn't be obvious from the start, and unless I copy-paste the filename after a `dir` it may be painful.

I wonder how others have worked around this. Maybe an escape char? or a different one altogether?

2022-01-26 12:14 UTC, ereslibre commented
> I wonder how others have worked around this. Maybe an escape char? or a different one altogether?

It depends. Docker for example follows a complete different storage scheme where they use the SHA's of the layers to store this information, and then the name of repos/images and tags is just data on top of that. We, for the sake of simplicity went with the 1:1 filesystem/URL hierarchy mapping.

I have been discussing with @nunix because another option would be to have a different layout on Windows, such as:

```
/home/ereslibre/.cache/kubewarden/store
└── registry
    └── ghcr.io
        └── kubewarden
            └── policies
                └── pod-privileged
                    └── v0.1.9
```

as opposed to the one in Unix:

```
/home/ereslibre/.cache/kubewarden/store
└── registry
    └── ghcr.io
        └── kubewarden
            └── policies
                └── pod-privileged:v0.1.9
```

I think this might be the most clear solution but it involves a bit of more special case handling for the Windows case.

We (@nunix and I) have settled on keeping this PR and aim for the hierarchical change in the near future.

2022-01-27 15:33 UTC, ereslibre commented
This implementation has been updated as discussed on yesterdays standup.

On Unix systems, the store is unchanged. On Windows systems, base62 is used for the name of directories and folders.

2022-01-27 18:18 UTC, flavio requested changes
Overall good. I left some comments.

Can you also add some unit tests? It would be great to have some way to test the encoding produced by these "build the path" functions.

2022-01-27 18:18 UTC, flavio commented on src/store.rs
> +        let filename: String = base_62::encode(filename.to_string().as_bytes());
Add some documentation to the function that explains the purpose of this function but, most important of all, the different behaviour on windows. What are we doing on Win and why.

2022-01-27 18:18 UTC, flavio commented on src/store.rs
> +        let host_and_port = base_62::encode(host_and_port.to_string().as_bytes());
Add some documentation to the function that explains the purpose of this function but, most important of all, the different behaviour on windows. What are we doing on Win and why.

2022-01-27 18:18 UTC, flavio commented on src/store.rs
> +        let path: String = base_62::encode(path.as_bytes());
Add some documentation to the function that explains the purpose of this function but, most important of all, the different behaviour on windows. What are we doing on Win and why.

2022-01-27 18:18 UTC, flavio commented on src/store.rs
> +                                    PathBuf::from("/").join(policy_store_path.collect::<PathBuf>());
I think it would be better to have this logic moved into dedicated functions. Both functions would have the same name, but only one would be visible depending on the `target_os`

2022-01-28 18:31 UTC, ereslibre commented on src/store.rs
> +                                    PathBuf::from("/").join(policy_store_path.collect::<PathBuf>());
I have done something in between. Repeating the whole logic is troublesome for maintenance purposes as well, so the "main" logic is only written once, and the special case (whether to base62 or not) is moved to a function that basically is an identity operation on non windows environments, and base62 on windows.

2022-01-31 10:16 UTC, flavio approved these changes
LGTM, thanks for the changes!

2022-02-01 09:26 UTC, viccuad approved these changes
LGTM, yet looking forward to base64 (don't hesitate to re-request review).

2022-02-01 09:54 UTC, ereslibre commented
@viccuad I'm good to merge this now.

2022-02-01 10:02 UTC, viccuad approved these changes
LGTM! Thanks for the effort on this topic, and the function docs!

2022-02-01 10:04 UTC, merged