Validate wasm modules
kubewarden/policy-fetcher pull request #41
Opened 2022-02-02 11:30 UTC by raulcabello

fixes https://github.com/kubewarden/policy-fetcher/issues/15

2022-02-02 12:16 UTC, jvanz approved these changes
LGTM! :D

2022-02-02 13:06 UTC, viccuad approved these changes
LGTM besides one comment.

2022-02-02 14:35 UTC, raulcabello commented on src/lib.rs
> +    match Module::validate(&Engine::default(), buf) {
I think this engine is already a wasmtime engine https://github.com/raulcabello/policy-fetcher/blob/d6b9319de47e32aaa9700810e3bab16aeaa47b8d/src/lib.rs#L32 or do you mean not use the default one?

2022-02-02 15:17 UTC, ereslibre requested changes
Thanks @raulcabello!

In general I think it is fine, but I think we can do an improvement to where the validation happens and how it happens.

2022-02-02 15:17 UTC, ereslibre commented on src/https.rs
> +        validate_wasm(&buf)?;
I think it would be good to attempt a slightly different approach.

On https://github.com/kubewarden/policy-fetcher/blob/main/src/lib.rs#L40, when we call to `.fetch()`, we do so with a temporary file that we have created beforehand.

We inspect the temporary file. If it's not a valid Wasm module, we error out, otherwise we move it to the final destination and everything is fine.

I think it's a slightly better approach because the `validate_wasm` is not called by every backend but by the toplevel logic.

What do you think?

2022-02-02 16:35 UTC, raulcabello commented on src/https.rs
> +        validate_wasm(&buf)?;
Thanks for the suggestion! I agree, it'd be better to call validate_wasm in the toplevel instead of calling it in each backend. But I don't find the temporary file that's created beforehand. That's why I made the call just before the file is created [here](https://github.com/raulcabello/policy-fetcher/blob/main/src/https.rs#L66) and [here](https://github.com/raulcabello/policy-fetcher/blob/main/src/registry/mod.rs#L276) so we avoid having to create the file and then delete it if there was an error. 

On a separate topic, I just noticed we are fetching the wasm file twice [here](https://github.com/raulcabello/policy-fetcher/blob/main/src/lib.rs#L97) and [here](https://github.com/raulcabello/policy-fetcher/blob/main/src/lib.rs#L110) (maybe 3 times [here](https://github.com/raulcabello/policy-fetcher/blob/main/src/lib.rs#L110) if we use tls too?) I put a println inside the https fetch method and I verified it's been called twice. I'll create an issue for this

2022-02-02 17:58 UTC, ereslibre commented on src/https.rs
> +        validate_wasm(&buf)?;
Yes, this is in purpose. We behave as Docker does. The idea is:

1. We try to download the module with https and valid certificates
2. If the server is marked as insecure
    1. We try with https without checking certificates
    2. We try with http

This is akin to https://docs.docker.com/registry/insecure/

2022-02-03 08:31 UTC, raulcabello commented on src/https.rs
> +        validate_wasm(&buf)?;
Thanks for the explanation, it makes more sense now. Anyway I still think we are calling it twice. Shouldn't we return OK if the first [fetch](https://github.com/raulcabello/policy-fetcher/blob/main/src/lib.rs#L97) is successful? As we don't return ok in the first fetch, the second will be tried and it will override the destination. 

Coming back to your original suggestion, I can't find the temporary file. That's why I make the call just before the file is created [here](https://github.com/raulcabello/policy-fetcher/blob/main/src/https.rs#L66) and [here](https://github.com/raulcabello/policy-fetcher/blob/main/src/registry/mod.rs#L276) so we avoid having to create the file and then delete it if there was an error. Where would you place the `validate_wasm` call in the toplevel logic? Sorry about diverting the original conversation

2022-02-03 08:51 UTC, ereslibre commented on src/https.rs
> +        validate_wasm(&buf)?;
You are right, the first case is wrong and needs a match. The idea is to return early if succeeded, or if failed and is not an insecure registry. Otherwise, we continue with the rest of the retries.

> Coming back to your original suggestion, I can't find the temporary file

I explained myself extremely poorly. We are not doing this already, I was meaning to do that in this PR: create the temporary file, write the module to it, inspect the module. If the module is fine, we move it to the final location and succeed. If the module is wrong, we delete the temporary file and return error.

My idea was that the `File::create` in https://github.com/raulcabello/policy-fetcher/blob/d6b9319de47e32aaa9700810e3bab16aeaa47b8d/src/https.rs#L66 and https://github.com/raulcabello/policy-fetcher/blob/d6b9319de47e32aaa9700810e3bab16aeaa47b8d/src/registry/mod.rs#L277 is targeting the temporary file that has been created by https://github.com/raulcabello/policy-fetcher/blob/d6b9319de47e32aaa9700810e3bab16aeaa47b8d/src/lib.rs#L41 in advance.

So, summing up:

1. `fetch_policy` creates a temporary file, calls to the backend that matches with the temporary file path as the destination.
2. The backend does its thing and writes the contents to the destination, without knowing where that file is (is a temporary file, not a file in the real store, but the backend does not care).
3. The file is inspected back in `fetch_policy` or an utility function called by it.
4. If it's fine, the file is moved by `fetch_policy` or an utility function to the real place in the store and success is returned.
5. If it's corrupt, the file is removed by `fetch_policy` or an utility function and an error is reported back to the caller.

2022-02-03 08:53 UTC, ereslibre commented on src/https.rs
> +        validate_wasm(&buf)?;
As an aside that I didn't answer. I think is fine to create a temporary file and discard it so we don't have to validate on every backend. Is true that not many backends will be needed and this might seem unnecessary, but I think doing the validation of the Wasm check belongs on an upper level where this logic is shared, instead of explicitly on each backend.

2022-02-03 09:38 UTC, viccuad commented on src/lib.rs
> +    match Module::validate(&Engine::default(), buf) {
doh, indeed! thanks for the pointer, disregard this.

2022-02-04 11:49 UTC, ereslibre reviewed
Thank you @raulcabello! Looking great! I love when a new feature is implemented and the code diff is net negative! Kudos!

Some comments.

2022-02-04 11:49 UTC, ereslibre commented on src/fetcher.rs
> +use bytes::Bytes;
I don't think we need `Bytes`. It's a data structure that implements some optimizations for working with the data directly. However, in our case, we just want to move whole byte streams around.

I would replace it with `Vec<u8>`, unless there is a strong reason not do so so.

2022-02-04 11:49 UTC, ereslibre commented on src/https.rs
>          let buf = client.get(url.as_ref()).send().await?.bytes().await?;
```suggestion
        client.get(url.as_ref()).send().await?.bytes().await
```

2022-02-04 11:49 UTC, ereslibre commented on src/https.rs
>          let buf = client.get(url.as_ref()).send().await?.bytes().await?;
And you can get rid of `Ok(buf)`.

2022-02-04 11:49 UTC, ereslibre commented on src/fetcher.rs
>      // Download the WASM module to the provided destination
Update comment

2022-02-04 12:56 UTC, raulcabello commented on src/fetcher.rs
>      // Download the WASM module to the provided destination
done in https://github.com/kubewarden/policy-fetcher/pull/41/commits/75d7fa1c34c26d86b04e52fce9938e9d71f9d1c1

2022-02-04 12:56 UTC, ereslibre approved these changes
👏

2022-02-04 12:56 UTC, raulcabello commented on src/https.rs
>          let buf = client.get(url.as_ref()).send().await?.bytes().await?;
done in https://github.com/kubewarden/policy-fetcher/pull/41/commits/75d7fa1c34c26d86b04e52fce9938e9d71f9d1c1

2022-02-04 12:57 UTC, raulcabello commented on src/fetcher.rs
> +use bytes::Bytes;
done in https://github.com/kubewarden/policy-fetcher/pull/41/commits/75d7fa1c34c26d86b04e52fce9938e9d71f9d1c1

2022-02-04 14:48 UTC, merged