feat: Add pub `verify_pub_keys()`, `verify_keyless_exact_match()`
kubewarden/policy-fetcher pull request #79
Opened 2022-04-14 11:01 UTC by viccuad

## Description

Fix https://github.com/kubewarden/policy-server/issues/99
Supersedes https://github.com/kubewarden/policy-fetcher/pull/77

- Add pub functions `verify_pub_keys()`, `verify_keyless_exact_match()`. These are shims that translate to an interim `VerificationConfig` and call `verify()`, so only 1 codepath exists, no need for tests.
- re-export kubewarden_policy_sdk through policy-fetcher for consumption.
- Minor refactors and error checking.

2022-04-20 16:15 UTC, flavio commented
Ok, I looked into the PR and I understand your comment. I didn't expect the code to reuse the verification primitives of policy-fetcher. Given the limited API offered to the end user, I was expecting to see something written on top of "pure sigstore", plus some little duplicated code. I understand why you went this way.

At the same time, I think it's just a bit strange to me to have the `policy-sdk` requirement be moved from `policy-evaluator` to `policy-fetcher`. Moreover it's strange for me to look for the implementation details of an exposed callback function not into `policy-evaluator`, but `policy-fetcher`.
I also think it would be annoying to implement fixes to the verification APIs, because would have to touch `policy-fetcher` and then `policy-evaluator`.

Being pragmatic, for the end user there's no difference. This is definitely a matter of personal taste. I'm fine leaving the code as it currently is. We can always change that in the future without breaking user policies.

2022-04-20 16:19 UTC, raulcabello commented
We are sharing some code with the policy validation such as `FulcioAndRekorData` and `cosign client` creation in `Verifier`. We could move the two methods `verify_pub_keys()` and  `verify_keyless_exact_match() `to the evaluator and still reuse the verify code in the `Verifier`.

However,  I think it conceptually makes more sense to have all verify functions together in the `Verifier` struct in `policy-fetcher`. This would help with refactors or changes in VerificationConfig as @viccuad pointed out.

2022-04-20 16:21 UTC, flavio approved these changes
LGTM, as I stated I would have moved the code into `policy-evalutor`, but this is a matter of personal taste

2022-04-22 07:41 UTC, viccuad reviewed
Raul's new changes LGTM, thanks! and thanks for the sigstore registry change, forgot about it.

2022-04-22 11:38 UTC, viccuad commented
Still, now we don't need to re-export the SDK through policy-fetcher, nor consume it in evaluator.

2022-04-22 12:27 UTC, raulcabello commented
@viccuad we still needed [here](https://github.com/raulcabello/policy-evaluator/blob/sigstore_container_verification3/src/callback_handler/mod.rs#L10-L13) for the `CallbackRequestType`, `KeylessInfo` and `VerificationResponse`

2022-04-25 08:42 UTC, viccuad commented
Rebased main, and consumed policy-sdk-rust from Raúl's branch, of the other PR, for now.

2022-04-26 13:04 UTC, flavio requested changes

2022-04-26 13:04 UTC, flavio commented on src/verify/mod.rs
> +    }
This method is causes the `policy-sdk` dependency to be inside of `policy-fetcher`. Given this method leverages the public `verify` method, can't we simply move it into `policy-evaluator`?

In that way we will get rid of the `policy-sdk` dependency

2022-04-26 13:09 UTC, raulcabello commented on src/verify/mod.rs
> +    }
that was done, but I can't see that change here anymore. I still see the commit in my local though..

2022-04-26 13:15 UTC, raulcabello commented on src/verify/mod.rs
> +    }
it was done [here](https://github.com/kubewarden/policy-fetcher/commit/a1f46afdefc0c1de9958379373cd26d3a029223a)

2022-04-26 13:30 UTC, flavio commented on src/verify/mod.rs
> +    }
There's something wrong with the PR then, when I open your link I get a big warning at the top of it:

> **This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.**

2022-04-26 13:45 UTC, flavio approved these changes
LGTM, I love how small this change turned out to be

2022-04-26 14:42 UTC, viccuad commented on src/verify/mod.rs
> -    /// that are stored inside of OCI registries.
this commentary has disappeared.

2022-04-26 14:42 UTC, viccuad commented on src/verify/mod.rs
> -    /// that are stored inside of OCI registries.
Reinstated in https://github.com/kubewarden/policy-fetcher/pull/79/commits/3ead76d6c18f91e3e1160a1fca7781693dbdc145.

2022-04-26 14:54 UTC, flavio approved these changes

2022-04-26 17:35 UTC, jvanz approved these changes

2022-04-27 15:29 UTC, merged